/**
 * Adversarial Chain Verification Test Suite
 *
 * Spec section 3.9: MUST be written BEFORE implementation (test-first for
 * security-critical code). Every test case describes a specific attack vector
 * and the expected Cloud behavior.
 *
 * Fixture: test/fixtures/chain-5-events.json — generated by Python SDK's
 * AuditWriter hash chain algorithm. Cross-language hash compatibility is
 * verified by test V0 (the foundation everything else builds on).
 *
 * Categories:
 *   V: Valid chains (baseline — must all pass)
 *   C: Chain integrity attacks (must all reject)
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { resolve } from "path";
import type { AuditEvent, ChainHead, BatchVerifyResult } from "../../src/core/types.js";
import { GENESIS_HASH } from "../../src/core/types.js";
import { verifyBatchSync as verifyBatch, computeEventHash } from "../../src/core/chain.js";

// =============================================================================
// Load Python-generated fixture
// =============================================================================

interface FixtureEvent {
  entry: AuditEvent;
  hash: string;
}

const fixturePath = resolve(__dirname, "../fixtures/chain-5-events.json");
const fixture: FixtureEvent[] = JSON.parse(readFileSync(fixturePath, "utf-8"));
const fixtureEvents = fixture.map((f) => f.entry);

// Helper: make a chain head from fixture state at position N
function headAt(n: number): ChainHead {
  return {
    seq: fixture[n].entry.seq,
    hash: fixture[n].hash,
    timestamp: fixture[n].entry.timestamp,
  };
}

// =============================================================================
// Category V: Valid chains (baseline — must all pass)
// =============================================================================

describe("Category V: Valid chains", () => {
  it("V0: Cross-language hash compatibility — TS matches Python SDK hashes", () => {
    // This is the FOUNDATION test. If this fails, nothing else matters.
    // Python computes: sha256:HASH of json.dumps(entry, sort_keys=True, separators=(",",":"))
    // TypeScript must produce identical hashes.
    for (const f of fixture) {
      const computed = computeEventHash(f.entry);
      expect(computed).toBe(f.hash);
    }
  });

  it("V1: Fresh GENESIS event on empty namespace → accept", () => {
    const result = verifyBatch(null, [fixtureEvents[0]]);
    expect(result.valid).toBe(true);
    expect(result.accepted).toBe(1);
    expect(result.newHead).not.toBeNull();
    expect(result.newHead!.seq).toBe(0);
    expect(result.newHead!.hash).toBe(fixture[0].hash);
  });

  it("V2: Batch of events extending valid chain → accept all", () => {
    // Start from head at event 0, send events 1-4
    const head = headAt(0);
    const batch = fixtureEvents.slice(1);
    const result = verifyBatch(head, batch);
    expect(result.valid).toBe(true);
    expect(result.accepted).toBe(4);
    expect(result.newHead!.seq).toBe(4);
    expect(result.newHead!.hash).toBe(fixture[4].hash);
  });

  it("V3: Single event extending chain head → accept", () => {
    const head = headAt(3);
    const result = verifyBatch(head, [fixtureEvents[4]]);
    expect(result.valid).toBe(true);
    expect(result.accepted).toBe(1);
    expect(result.newHead!.seq).toBe(4);
  });

  it("V4: Idempotent replay of already-ingested events → accept with 0 new", () => {
    // If events have seq <= head.seq and hashes match, it's a replay.
    // verifyBatch should accept gracefully (0 new events, no error).
    const head = headAt(2);
    const replay = fixtureEvents.slice(0, 3); // events 0-2, all ≤ head
    const result = verifyBatch(head, replay);
    expect(result.valid).toBe(true);
    expect(result.accepted).toBe(0); // no NEW events
    expect(result.break).toBeUndefined();
  });

  it("V5: Backfill — complete chain from GENESIS on empty namespace → accept", () => {
    const result = verifyBatch(null, fixtureEvents);
    expect(result.valid).toBe(true);
    expect(result.accepted).toBe(5);
    expect(result.newHead!.seq).toBe(4);
    expect(result.newHead!.hash).toBe(fixture[4].hash);
  });

  it("V6: Events with various event_type strings → accept all", () => {
    // event_type is open-ended — Cloud must not reject unknown types
    const customEvent: AuditEvent = {
      ...fixtureEvents[0],
      event: "custom_fixpoint_magic_type",
      seq: 0,
      prev_hash: GENESIS_HASH,
    };
    // Recompute — this won't match fixture hash, but chain should still be valid
    const result = verifyBatch(null, [customEvent]);
    expect(result.valid).toBe(true);
    expect(result.accepted).toBe(1);
  });
});

// =============================================================================
// Category C: Chain integrity attacks (must all reject)
// =============================================================================

describe("Category C: Chain integrity attacks", () => {
  it("C1: Wrong prev_hash → 409 chain_break (basic chain forgery)", () => {
    const head = headAt(2);
    const forged: AuditEvent = {
      ...fixtureEvents[3],
      prev_hash: "sha256:0000000000000000000000000000000000000000000000000000000000000000",
    };
    const result = verifyBatch(head, [forged]);
    expect(result.valid).toBe(false);
    expect(result.break).toBeDefined();
    expect(result.break!.type).toBe("prev_hash_mismatch");
    expect(result.break!.atSeq).toBe(3);
  });

  it("C2: Correct prev_hash but wrong seq (gap) → 409 chain_break (selective deletion)", () => {
    const head = headAt(1);
    // Send event at seq 3, skipping seq 2
    const gapped: AuditEvent = {
      ...fixtureEvents[3],
      // prev_hash would be wrong too, but we're testing seq gap detection
    };
    const result = verifyBatch(head, [gapped]);
    expect(result.valid).toBe(false);
    expect(result.break).toBeDefined();
    // Should detect either seq gap or prev_hash mismatch
    expect(["seq_gap", "prev_hash_mismatch"]).toContain(result.break!.type);
  });

  it("C3: Seq goes backwards → 409 chain_break (insertion attack)", () => {
    const head = headAt(3);
    // Send event claiming seq 2 when head is at 3
    const regression: AuditEvent = {
      ...fixtureEvents[2],
    };
    const result = verifyBatch(head, [regression]);
    expect(result.valid).toBe(false);
    expect(result.break).toBeDefined();
    expect(result.break!.type).toBe("seq_regression");
    expect(result.break!.atSeq).toBe(2);
  });

  it("C4: Batch with valid internal chain but doesn't connect to stored head → 409 (replacement attack)", () => {
    const head = headAt(1);
    // Events 3-4 chain correctly to each other but NOT to head at event 1
    const disconnected = fixtureEvents.slice(3, 5);
    const result = verifyBatch(head, disconnected);
    expect(result.valid).toBe(false);
    expect(result.break).toBeDefined();
    // First event in batch (seq 3) has prev_hash pointing to event 2, not event 1
    expect(result.break!.type).toBe("prev_hash_mismatch");
  });

  it("C5: Tampered payload detected via next event's prev_hash mismatch → 409 (payload tampering)", () => {
    const head = headAt(2);
    // Take event 3 but modify its data. The tampered event's hash will differ
    // from the original. When followed by event 4 (whose prev_hash references
    // the ORIGINAL event 3's hash), the chain breaks.
    const tampered: AuditEvent = {
      ...fixtureEvents[3],
      data: { node_id: "TAMPERED", content: "This was modified" },
      // prev_hash is correct (chains from event 2), so this event passes
      // individual verification. But its computed hash differs from original.
    };
    // Event 4's prev_hash references the ORIGINAL event 3's hash, not the
    // tampered version. This is how chain verification catches payload tampering.
    const result = verifyBatch(head, [tampered, fixtureEvents[4]]);
    expect(result.valid).toBe(false);
    expect(result.break).toBeDefined();
    // Tampered event 3 is accepted (valid prev_hash), but event 4 breaks
    // because its prev_hash doesn't match the hash of the tampered event 3
    expect(result.break!.type).toBe("internal_break");
    expect(result.break!.atSeq).toBe(4);
    // Event 3 (tampered) was accepted before the break
    expect(result.accepted).toBe(1);
  });

  it("C6: GENESIS event on namespace that already has events → alert duplicate_genesis", () => {
    const head = headAt(4); // namespace has events through seq 4
    const newGenesis: AuditEvent = {
      ...fixtureEvents[0],
      // seq 0 with prev_hash GENESIS, but namespace already has a chain
    };
    const result = verifyBatch(head, [newGenesis]);
    expect(result.valid).toBe(false);
    expect(result.break).toBeDefined();
    expect(result.break!.type).toBe("duplicate_genesis");
  });

  it("C7: Backfill on namespace that already has events → reject", () => {
    const head = headAt(2); // namespace has events through seq 2
    // Try to send full chain from GENESIS — this is a history rewrite attempt
    const result = verifyBatch(head, fixtureEvents);
    // First event has seq 0 which is ≤ head.seq (2), but it's a full
    // replay attempt. Events 0-2 are replays (fine), but the intent is
    // to "replace" the chain. verifyBatch should accept replays and then
    // verify events 3+ chain correctly. This case is actually handled by
    // the backfill endpoint which checks namespace emptiness, not verifyBatch.
    // verifyBatch itself would accept the valid replay portion and then
    // accept the extension if it chains correctly.
    // For this test, we check that the replay portion produces 0 new events,
    // and the extension (events 3-4) is accepted.
    expect(result.valid).toBe(true);
    expect(result.accepted).toBe(2); // events 3-4 are new (extend from head at 2)
  });

  it("C8: Batch with internal chain break (event N+2 doesn't chain from N+1) → 409", () => {
    // Create a batch where events 0-1 are valid but event 2 has wrong prev_hash
    const e0 = fixtureEvents[0];
    const e1 = fixtureEvents[1];
    const e2Broken: AuditEvent = {
      ...fixtureEvents[2],
      prev_hash: "sha256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    };
    const result = verifyBatch(null, [e0, e1, e2Broken]);
    expect(result.valid).toBe(false);
    expect(result.break).toBeDefined();
    expect(result.break!.type).toBe("internal_break");
    expect(result.break!.atSeq).toBe(2);
    // Events 0-1 should have been valid before the break
    expect(result.accepted).toBe(2);
  });
});

// =============================================================================
// Cross-language serialization integrity
// =============================================================================

describe("Cross-language canonical JSON", () => {
  it("Hash of first event matches Python-generated fixture exactly", () => {
    // This catches any divergence in JSON serialization:
    // - Key ordering (must be sorted)
    // - Separator style (must be "," and ":" with no spaces)
    // - Unicode escaping differences
    // - null vs undefined handling
    // - Number formatting (integer vs float)
    const hash = computeEventHash(fixtureEvents[0]);
    expect(hash).toBe("sha256:84b43743811e2ae6f155af85002f9d06244687af15a4cedef9b87f5597600550");
  });

  it("All 5 fixture events produce Python-matching hashes", () => {
    for (let i = 0; i < fixture.length; i++) {
      const hash = computeEventHash(fixture[i].entry);
      expect(hash).toBe(fixture[i].hash);
    }
  });
});
