/**
 * Edge Case Serialization Tests — Cross-language hash compatibility.
 *
 * These test the SPECIFIC serialization divergences between Python and JS
 * that could silently break hash chain verification.
 *
 * Python fixture generated by: json.dumps(entry, sort_keys=True, separators=(",",":"))
 * Hashes verified against Python's hashlib.sha256.
 */

import { describe, it, expect } from "vitest";
import type { AuditEvent } from "../../src/core/types.js";
import { computeEventHash, computeStringHash, verifyBatchFromStrings } from "../../src/core/chain.js";

describe("Cross-language edge cases", () => {

  it("CRITICAL: whole-number float — parsed objects DIVERGE (known, documented)", () => {
    // Python json.dumps outputs 1.0 for float(1), JS JSON.stringify outputs 1.
    // Parsing the Python JSON via JSON.parse loses this distinction permanently.
    // This is WHY we use raw string hashing in production.
    const event: AuditEvent = {
      v: 1,
      seq: 0,
      timestamp: "2026-03-28T12:00:00+00:00",
      event: "edge_case_test",
      prev_hash: "sha256:GENESIS",
      session_id: "sess_edge",
      data: { type: "float_whole", temperature: 1.0, score: 0.0 },
      adapter: null,
    };

    const tsHash = computeEventHash(event);
    const pythonHash = "sha256:2242f69f31d1fae801499305ab97ec553653185df3907eff6416cfe2b077b7ba";

    // EXPECTED TO FAIL — this documents the known divergence.
    // Production uses computeStringHash on raw SDK strings, not computeEventHash.
    expect(tsHash).not.toBe(pythonHash);
  });

  it("CRITICAL: whole-number float — RAW STRING hashing MATCHES (production path)", () => {
    // The PRODUCTION code path: hash the raw canonical JSON string from the SDK.
    // No JSON.parse roundtrip. Preserves Python's "1.0" formatting exactly.
    const pythonCanonicalJson = '{"adapter":null,"data":{"score":0.0,"temperature":1.0,"type":"float_whole"},"event":"edge_case_test","prev_hash":"sha256:GENESIS","seq":0,"session_id":"sess_edge","timestamp":"2026-03-28T12:00:00+00:00","v":1}';
    const pythonHash = "sha256:2242f69f31d1fae801499305ab97ec553653185df3907eff6416cfe2b077b7ba";

    // Hash the raw string — this is what Cloud does in production
    const cloudHash = computeStringHash(pythonCanonicalJson);
    expect(cloudHash).toBe(pythonHash);
  });

  it("CRITICAL: full chain with floats verified via verifyBatchFromStrings", () => {
    // Simulate what production does: receive raw JSON strings, parse for metadata,
    // verify chain using raw string hashes.
    const pythonStrings = [
      '{"adapter":null,"data":{"score":0.0,"temperature":1.0,"type":"float_whole"},"event":"edge_case_test","prev_hash":"sha256:GENESIS","seq":0,"session_id":"sess_edge","timestamp":"2026-03-28T12:00:00+00:00","v":1}',
      '{"adapter":null,"data":{"confidence":0.95,"pi":3.14159,"threshold":0.001,"type":"float_decimal"},"event":"edge_case_test","prev_hash":"sha256:2242f69f31d1fae801499305ab97ec553653185df3907eff6416cfe2b077b7ba","seq":1,"session_id":"sess_edge","timestamp":"2026-03-28T12:01:00+00:00","v":1}',
    ];
    const parsed = pythonStrings.map((s) => JSON.parse(s) as AuditEvent);

    // This is the production verification path
    const result = verifyBatchFromStrings(null, pythonStrings, parsed);
    expect(result.valid).toBe(true);
    expect(result.accepted).toBe(2);
    expect(result.newHead).not.toBeNull();
  });

  it("Decimal floats (0.95, 0.001, 3.14159)", () => {
    const event: AuditEvent = {
      v: 1,
      seq: 1,
      timestamp: "2026-03-28T12:01:00+00:00",
      event: "edge_case_test",
      prev_hash: "sha256:2242f69f31d1fae801499305ab97ec553653185df3907eff6416cfe2b077b7ba",
      session_id: "sess_edge",
      data: { type: "float_decimal", confidence: 0.95, threshold: 0.001, pi: 3.14159 },
      adapter: null,
    };
    const pythonHash = "sha256:8661f7f8c39454b2c7c7eb67470ca635b2f4b8371f74c566cfc966c7bb456799";
    expect(computeEventHash(event)).toBe(pythonHash);
  });

  it("Nested objects with unsorted keys (key ordering at depth)", () => {
    const event: AuditEvent = {
      v: 1,
      seq: 2,
      timestamp: "2026-03-28T12:02:00+00:00",
      event: "edge_case_test",
      prev_hash: "sha256:8661f7f8c39454b2c7c7eb67470ca635b2f4b8371f74c566cfc966c7bb456799",
      session_id: "sess_edge",
      data: { type: "nested", outer: { zebra: 1, alpha: 2, inner: { z: true, a: false } } },
      adapter: null,
    };
    const pythonHash = "sha256:dc8430ab6bc3c5a95023a3c14594d19a01519bb26dee7d6519285f1f075cdee1";
    expect(computeEventHash(event)).toBe(pythonHash);
  });

  it("Empty containers ({}, [], '')", () => {
    const event: AuditEvent = {
      v: 1,
      seq: 3,
      timestamp: "2026-03-28T12:03:00+00:00",
      event: "edge_case_test",
      prev_hash: "sha256:dc8430ab6bc3c5a95023a3c14594d19a01519bb26dee7d6519285f1f075cdee1",
      session_id: "sess_edge",
      data: { type: "empty", empty_obj: {}, empty_arr: [], empty_str: "" },
      adapter: null,
    };
    const pythonHash = "sha256:8acd254684e855c1a8f57627165052d3e5ba1cd2f92dba26958f0e2323d25987";
    expect(computeEventHash(event)).toBe(pythonHash);
  });

  it("Booleans and null", () => {
    const event: AuditEvent = {
      v: 1,
      seq: 4,
      timestamp: "2026-03-28T12:04:00+00:00",
      event: "edge_case_test",
      prev_hash: "sha256:8acd254684e855c1a8f57627165052d3e5ba1cd2f92dba26958f0e2323d25987",
      session_id: "sess_edge",
      data: { type: "bool_null", flag: true, other: false, nothing: null },
      adapter: null,
    };
    const pythonHash = "sha256:1a66cd4c54251507da40727ed1e76c3a758e15100aaffee1045908bf4381bc42";
    expect(computeEventHash(event)).toBe(pythonHash);
  });

  it("Large integers and negatives", () => {
    const event: AuditEvent = {
      v: 1,
      seq: 6,
      timestamp: "2026-03-28T12:06:00+00:00",
      event: "edge_case_test",
      prev_hash: "sha256:d9b1ada1e761f9501b13bd3a506863d8d2455855197895d691bc8f6e59c36fc9",
      session_id: "sess_edge",
      data: { type: "large_int", count: 1000000, negative: -42 },
      adapter: null,
    };
    const pythonHash = "sha256:a71a00d65934646390f7f2e63cc3ebd5b494930bd84d4d7683996dd97bc9c62d";
    expect(computeEventHash(event)).toBe(pythonHash);
  });
});
